/*
 * PWM.h
 *
 *  Created on: 2016/02/15
 *      Author: evaota
 */

#ifndef PWM_H_
#define PWM_H_

#include "LPC11xx.h"
#include "Timer16_32.h"
#include <stdint.h>

#define SETDUTY0TMR16B0(Duty) LPC_TMR16B0->MR0 = Duty
#define SETDUTY1TMR16B0(Duty) LPC_TMR16B0->MR1 = Duty

#define SETDUTY0TMR16B1(Duty) LPC_TMR16B1->MR0 = Duty

#define SETDUTY0TMR32B0(Duty) LPC_TMR32B0->MR0 = Duty
#define SETDUTY2TMR32B0(Duty) LPC_TMR32B0->MR2 = Duty
#define SETDUTY3TMR32B0(Duty) LPC_TMR32B0->MR3 = Duty

#define SETDUTY0TMR32B1(Duty) LPC_TMR32B1->MR0 = Duty
#define SETDUTY1TMR32B1(Duty) LPC_TMR32B1->MR1 = Duty
#define SETDUTY3TMR32B1(Duty) LPC_TMR32B1->MR3 = Duty

//User must define Timer16_32.h
//frequency range is 60Hz~49kHz
//*Warning User must will set output and TIMERxBx_MATx mode on IOCON.
//These function won't generate interrupt.if you want to use interrput,define NVIC_IRQEnable(Handler);
void PWM16B0Init(uint32_t UserPR,uint32_t outpin);//pwm cycle is generated by MR3.LPC1114 don't exist CT16B0_MAT3 pin,
//**WARNING don't use LPC_IOCON->SWCLK_PIO0_10.SWD won't be able to use.
//UserPR set OutPut frequency freq = 0.00002046(s)*UserPR
//outpin bit 0 : MAT0 bit1: MAT1 when each bit what is 1 is PWM mode.
void PWM16B1Init(uint32_t UserPR,uint32_t outpin);
//pwm cycle is generated by MR3.MAT1~MAT3 can't use PWM output,
//UserPR set OutPut frequency freq = 0.00002046(s)*UserPR
//outpin bit 0 : MAT0 when each bit what is 1 is PWM mode.
void PWM32B0Init(uint32_t UserPR,uint32_t outpin);//pwm cycle is generated by MR1.MAT1 can't use PWM output,because MAT1 is UART with TX pin
//UserPR set OutPut frequency freq = 0.00002046(s)*UserPR
//outpin bit 0 : MAT0 bit1: MAT2 bit3 : MAT3 when each bit what is 1 is PWM mode.
void PWM32B1Init(uint32_t UserPR,uint32_t outpin);//pwm cycle is generated by MR2.MAT2 can't use PWM output.
//UserPR set OutPut frequency freq = 0.00002046(s)*UserPR
//outpin bit 0 : MAT0 bit1: MAT1 bit3 : MAT3 when each bit what is 1 is PWM mode.

#endif /* PWM_H_ */
