/*
 * PWM.c
 *
 *  Created on: 2016/02/15
 *      Author: evaota
 */
#include "PWM.h"

void PWM16B0Init(uint32_t UserPR,uint32_t outpin)
{//pwm cycle is generated by MR3.LPC1114 don't exist CT16B0_MAT3 pin,
	ENABLETMR16B0CLK();//supplied system clock TIMER16B0
	SetMRxValue(TMR16B0,3,1023-1);//set PWM period,minimum cycle is 20us.
	MRxClearCT(TMR16B0,3);//Reset CT By MR3
	SetPrescal(TMR16B0,UserPR);//user count
	LPC_TMR16B0->PWMC |= (outpin<<0);//MAT0 IS PWM MODE
	SetMRxValue(TMR16B0,0,0);//clear output matching register
	SetMRxValue(TMR16B0,1,0);//clear output matching register
	TMRxStart(TMR16B0);//initialize timer
}
void PWM16B1Init(uint32_t UserPR,uint32_t outpin)
{//pwm cycle is generated by MR3.MAT1~MAT3 can't use PWM output,
	ENABLETMR16B1CLK();//supplied system clock TIMER16B1
	SetMRxValue(TMR16B1,3,1023-1);//set PWM period,minimum cycle is 20us.
	MRxClearCT(TMR16B1,3);//Reset CT By MR3
	SetPrescal(TMR16B1,UserPR);//user count
	LPC_TMR16B1->PWMC |= (outpin<<0);//MAT0 IS PWM MODE
	SetMRxValue(TMR16B1,0,0);//clear output matching register
	TMRxStart(TMR16B1);//initialize timer
}
void PWM32B0Init(uint32_t UserPR,uint32_t outpin)
{//pwm cycle is generated by MR1.MAT1 can't use PWM output,because MAT1 is used UART with TX pin
	ENABLETMR32B0CLK();//supplied system clock TIMER32B0
	SetMRxValue(TMR32B0,1,1023-1);//set PWM period,minimum cycle is 20us.
	MRxClearCT(TMR32B0,1);//Reset CT By MR1
	SetPrescal(TMR32B0,UserPR);//user count
		LPC_TMR32B0->PWMC |= (outpin<<0);//MAT0 IS PWM MODE
	SetMRxValue(TMR32B0,0,0);//clear output matching register
	SetMRxValue(TMR32B0,2,0);//clear output matching register
	SetMRxValue(TMR32B0,3,0);//clear output matching register
	TMRxStart(TMR32B0);//initialize timer
}
void PWM32B1Init(uint32_t UserPR,uint32_t outpin)//frequency range is 60Hz~49kHz
{//pwm cycle is generated by MR2.MAT2 can't use PWM output.
	ENABLETMR32B1CLK();//supplied system clock TIMER32B1
	SetMRxValue(TMR32B1,2,1023-1);//set PWM period,minimum cycle is 20us.
	MRxClearCT(TMR32B1,2);//Reset CT By MR2
	SetPrescal(TMR32B1,UserPR);//user count
	LPC_TMR32B1->PWMC |= (outpin<<0);//MAT3 IS PWM MODE
	SetMRxValue(TMR32B1,0,0);//clear output matching register
	SetMRxValue(TMR32B1,1,0);//clear output matching register
	SetMRxValue(TMR32B1,3,0);//clear output matching register
	TMRxStart(TMR32B1);//initialize timer
}
